name: "test-android-only"

on: 
  workflow_dispatch: # Manual trigger
  pull_request:
    paths:
      - 'flutter_app/**'
      - '.github/workflows/test-android-only.yml'

# This workflow will only build the Android app for testing purposes

jobs:
  test-android:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Node.js dependencies
        run: yarn install

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-platform: "android-33"
          build-tools: "33.0.1"

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'
          channel: 'stable'

      - name: Verify Flutter version
        run: flutter --version

      - name: Install Flutter dependencies with clean
        run: |
          cd flutter_app
          flutter clean
          flutter pub cache repair
          flutter pub get

      # Use the exact same command as in package.json for consistency
      - name: Build Android APK using package.json script pattern
        run: |
          # Export web assets
          yarn export
          
          # Create assets directory and zip output
          mkdir -p ./flutter_app/assets
          zip -r ./flutter_app/assets/out.zip out
          
          # Build APK
          cd ./flutter_app
          flutter build apk --release

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: flutter_app/build/app/outputs/flutter-apk/app-release.apk
          retention-days: 7
          
      # Optional: Build debug version for testing
      - name: Build Android APK (Debug)
        run: |
          cd flutter_app
          flutter build apk --debug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: flutter_app/build/app/outputs/flutter-apk/app-debug.apk
          retention-days: 7
